// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/LedgerSetFormats.proto

package org.apache.bookkeeper.proto;

public final class LedgerSetFormats {
  private LedgerSetFormats() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EntryIdFormatOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 ledger = 1;
    boolean hasLedger();
    long getLedger();
    
    // optional int64 entry = 2;
    boolean hasEntry();
    long getEntry();
  }
  public static final class EntryIdFormat extends
      com.google.protobuf.GeneratedMessage
      implements EntryIdFormatOrBuilder {
    // Use EntryIdFormat.newBuilder() to construct.
    private EntryIdFormat(Builder builder) {
      super(builder);
    }
    private EntryIdFormat(boolean noInit) {}
    
    private static final EntryIdFormat defaultInstance;
    public static EntryIdFormat getDefaultInstance() {
      return defaultInstance;
    }
    
    public EntryIdFormat getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.bookkeeper.proto.LedgerSetFormats.internal_static_EntryIdFormat_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.bookkeeper.proto.LedgerSetFormats.internal_static_EntryIdFormat_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 ledger = 1;
    public static final int LEDGER_FIELD_NUMBER = 1;
    private long ledger_;
    public boolean hasLedger() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getLedger() {
      return ledger_;
    }
    
    // optional int64 entry = 2;
    public static final int ENTRY_FIELD_NUMBER = 2;
    private long entry_;
    public boolean hasEntry() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getEntry() {
      return entry_;
    }
    
    private void initFields() {
      ledger_ = 0L;
      entry_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, ledger_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, entry_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, ledger_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, entry_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.bookkeeper.proto.LedgerSetFormats.internal_static_EntryIdFormat_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.bookkeeper.proto.LedgerSetFormats.internal_static_EntryIdFormat_fieldAccessorTable;
      }
      
      // Construct using org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ledger_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        entry_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat.getDescriptor();
      }
      
      public org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat getDefaultInstanceForType() {
        return org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat.getDefaultInstance();
      }
      
      public org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat build() {
        org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat buildPartial() {
        org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat result = new org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ledger_ = ledger_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.entry_ = entry_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat) {
          return mergeFrom((org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat other) {
        if (other == org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat.getDefaultInstance()) return this;
        if (other.hasLedger()) {
          setLedger(other.getLedger());
        }
        if (other.hasEntry()) {
          setEntry(other.getEntry());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ledger_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              entry_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 ledger = 1;
      private long ledger_ ;
      public boolean hasLedger() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getLedger() {
        return ledger_;
      }
      public Builder setLedger(long value) {
        bitField0_ |= 0x00000001;
        ledger_ = value;
        onChanged();
        return this;
      }
      public Builder clearLedger() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ledger_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 entry = 2;
      private long entry_ ;
      public boolean hasEntry() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getEntry() {
        return entry_;
      }
      public Builder setEntry(long value) {
        bitField0_ |= 0x00000002;
        entry_ = value;
        onChanged();
        return this;
      }
      public Builder clearEntry() {
        bitField0_ = (bitField0_ & ~0x00000002);
        entry_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:EntryIdFormat)
    }
    
    static {
      defaultInstance = new EntryIdFormat(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:EntryIdFormat)
  }
  
  public interface LedgerSetFormatOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated int64 ledger = 1;
    java.util.List<java.lang.Long> getLedgerList();
    int getLedgerCount();
    long getLedger(int index);
  }
  public static final class LedgerSetFormat extends
      com.google.protobuf.GeneratedMessage
      implements LedgerSetFormatOrBuilder {
    // Use LedgerSetFormat.newBuilder() to construct.
    private LedgerSetFormat(Builder builder) {
      super(builder);
    }
    private LedgerSetFormat(boolean noInit) {}
    
    private static final LedgerSetFormat defaultInstance;
    public static LedgerSetFormat getDefaultInstance() {
      return defaultInstance;
    }
    
    public LedgerSetFormat getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.bookkeeper.proto.LedgerSetFormats.internal_static_LedgerSetFormat_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.bookkeeper.proto.LedgerSetFormats.internal_static_LedgerSetFormat_fieldAccessorTable;
    }
    
    // repeated int64 ledger = 1;
    public static final int LEDGER_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> ledger_;
    public java.util.List<java.lang.Long>
        getLedgerList() {
      return ledger_;
    }
    public int getLedgerCount() {
      return ledger_.size();
    }
    public long getLedger(int index) {
      return ledger_.get(index);
    }
    
    private void initFields() {
      ledger_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < ledger_.size(); i++) {
        output.writeInt64(1, ledger_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < ledger_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(ledger_.get(i));
        }
        size += dataSize;
        size += 1 * getLedgerList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.bookkeeper.proto.LedgerSetFormats.internal_static_LedgerSetFormat_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.bookkeeper.proto.LedgerSetFormats.internal_static_LedgerSetFormat_fieldAccessorTable;
      }
      
      // Construct using org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ledger_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat.getDescriptor();
      }
      
      public org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat getDefaultInstanceForType() {
        return org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat.getDefaultInstance();
      }
      
      public org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat build() {
        org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat buildPartial() {
        org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat result = new org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          ledger_ = java.util.Collections.unmodifiableList(ledger_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ledger_ = ledger_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat) {
          return mergeFrom((org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat other) {
        if (other == org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat.getDefaultInstance()) return this;
        if (!other.ledger_.isEmpty()) {
          if (ledger_.isEmpty()) {
            ledger_ = other.ledger_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLedgerIsMutable();
            ledger_.addAll(other.ledger_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              ensureLedgerIsMutable();
              ledger_.add(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addLedger(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated int64 ledger = 1;
      private java.util.List<java.lang.Long> ledger_ = java.util.Collections.emptyList();;
      private void ensureLedgerIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          ledger_ = new java.util.ArrayList<java.lang.Long>(ledger_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<java.lang.Long>
          getLedgerList() {
        return java.util.Collections.unmodifiableList(ledger_);
      }
      public int getLedgerCount() {
        return ledger_.size();
      }
      public long getLedger(int index) {
        return ledger_.get(index);
      }
      public Builder setLedger(
          int index, long value) {
        ensureLedgerIsMutable();
        ledger_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addLedger(long value) {
        ensureLedgerIsMutable();
        ledger_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllLedger(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureLedgerIsMutable();
        super.addAll(values, ledger_);
        onChanged();
        return this;
      }
      public Builder clearLedger() {
        ledger_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:LedgerSetFormat)
    }
    
    static {
      defaultInstance = new LedgerSetFormat(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:LedgerSetFormat)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EntryIdFormat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EntryIdFormat_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LedgerSetFormat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LedgerSetFormat_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%src/main/proto/LedgerSetFormats.proto\"" +
      ".\n\rEntryIdFormat\022\016\n\006ledger\030\001 \001(\003\022\r\n\005entr" +
      "y\030\002 \001(\003\"!\n\017LedgerSetFormat\022\016\n\006ledger\030\001 \003" +
      "(\003B\037\n\033org.apache.bookkeeper.protoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_EntryIdFormat_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_EntryIdFormat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_EntryIdFormat_descriptor,
              new java.lang.String[] { "Ledger", "Entry", },
              org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat.class,
              org.apache.bookkeeper.proto.LedgerSetFormats.EntryIdFormat.Builder.class);
          internal_static_LedgerSetFormat_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_LedgerSetFormat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_LedgerSetFormat_descriptor,
              new java.lang.String[] { "Ledger", },
              org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat.class,
              org.apache.bookkeeper.proto.LedgerSetFormats.LedgerSetFormat.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
