// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/ZKMetaFormats.proto

package org.apache.bookkeeper.proto;

public final class ZKMetaFormats {
  private ZKMetaFormats() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MetastoreValueFormatOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .MetastoreFieldFormat field = 1;
    java.util.List<org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat> 
        getFieldList();
    org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat getField(int index);
    int getFieldCount();
    java.util.List<? extends org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormatOrBuilder> 
        getFieldOrBuilderList();
    org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormatOrBuilder getFieldOrBuilder(
        int index);
  }
  public static final class MetastoreValueFormat extends
      com.google.protobuf.GeneratedMessage
      implements MetastoreValueFormatOrBuilder {
    // Use MetastoreValueFormat.newBuilder() to construct.
    private MetastoreValueFormat(Builder builder) {
      super(builder);
    }
    private MetastoreValueFormat(boolean noInit) {}
    
    private static final MetastoreValueFormat defaultInstance;
    public static MetastoreValueFormat getDefaultInstance() {
      return defaultInstance;
    }
    
    public MetastoreValueFormat getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.bookkeeper.proto.ZKMetaFormats.internal_static_MetastoreValueFormat_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.bookkeeper.proto.ZKMetaFormats.internal_static_MetastoreValueFormat_fieldAccessorTable;
    }
    
    // repeated .MetastoreFieldFormat field = 1;
    public static final int FIELD_FIELD_NUMBER = 1;
    private java.util.List<org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat> field_;
    public java.util.List<org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat> getFieldList() {
      return field_;
    }
    public java.util.List<? extends org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormatOrBuilder> 
        getFieldOrBuilderList() {
      return field_;
    }
    public int getFieldCount() {
      return field_.size();
    }
    public org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat getField(int index) {
      return field_.get(index);
    }
    public org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormatOrBuilder getFieldOrBuilder(
        int index) {
      return field_.get(index);
    }
    
    private void initFields() {
      field_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < field_.size(); i++) {
        output.writeMessage(1, field_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < field_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, field_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.bookkeeper.proto.ZKMetaFormats.internal_static_MetastoreValueFormat_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.bookkeeper.proto.ZKMetaFormats.internal_static_MetastoreValueFormat_fieldAccessorTable;
      }
      
      // Construct using org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFieldFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (fieldBuilder_ == null) {
          field_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          fieldBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat.getDescriptor();
      }
      
      public org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat getDefaultInstanceForType() {
        return org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat.getDefaultInstance();
      }
      
      public org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat build() {
        org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat buildPartial() {
        org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat result = new org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat(this);
        int from_bitField0_ = bitField0_;
        if (fieldBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            field_ = java.util.Collections.unmodifiableList(field_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.field_ = field_;
        } else {
          result.field_ = fieldBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat) {
          return mergeFrom((org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat other) {
        if (other == org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat.getDefaultInstance()) return this;
        if (fieldBuilder_ == null) {
          if (!other.field_.isEmpty()) {
            if (field_.isEmpty()) {
              field_ = other.field_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFieldIsMutable();
              field_.addAll(other.field_);
            }
            onChanged();
          }
        } else {
          if (!other.field_.isEmpty()) {
            if (fieldBuilder_.isEmpty()) {
              fieldBuilder_.dispose();
              fieldBuilder_ = null;
              field_ = other.field_;
              bitField0_ = (bitField0_ & ~0x00000001);
              fieldBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFieldFieldBuilder() : null;
            } else {
              fieldBuilder_.addAllMessages(other.field_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.Builder subBuilder = org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addField(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .MetastoreFieldFormat field = 1;
      private java.util.List<org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat> field_ =
        java.util.Collections.emptyList();
      private void ensureFieldIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          field_ = new java.util.ArrayList<org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat>(field_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat, org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.Builder, org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormatOrBuilder> fieldBuilder_;
      
      public java.util.List<org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat> getFieldList() {
        if (fieldBuilder_ == null) {
          return java.util.Collections.unmodifiableList(field_);
        } else {
          return fieldBuilder_.getMessageList();
        }
      }
      public int getFieldCount() {
        if (fieldBuilder_ == null) {
          return field_.size();
        } else {
          return fieldBuilder_.getCount();
        }
      }
      public org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat getField(int index) {
        if (fieldBuilder_ == null) {
          return field_.get(index);
        } else {
          return fieldBuilder_.getMessage(index);
        }
      }
      public Builder setField(
          int index, org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat value) {
        if (fieldBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldIsMutable();
          field_.set(index, value);
          onChanged();
        } else {
          fieldBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setField(
          int index, org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.Builder builderForValue) {
        if (fieldBuilder_ == null) {
          ensureFieldIsMutable();
          field_.set(index, builderForValue.build());
          onChanged();
        } else {
          fieldBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addField(org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat value) {
        if (fieldBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldIsMutable();
          field_.add(value);
          onChanged();
        } else {
          fieldBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addField(
          int index, org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat value) {
        if (fieldBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFieldIsMutable();
          field_.add(index, value);
          onChanged();
        } else {
          fieldBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addField(
          org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.Builder builderForValue) {
        if (fieldBuilder_ == null) {
          ensureFieldIsMutable();
          field_.add(builderForValue.build());
          onChanged();
        } else {
          fieldBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addField(
          int index, org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.Builder builderForValue) {
        if (fieldBuilder_ == null) {
          ensureFieldIsMutable();
          field_.add(index, builderForValue.build());
          onChanged();
        } else {
          fieldBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllField(
          java.lang.Iterable<? extends org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat> values) {
        if (fieldBuilder_ == null) {
          ensureFieldIsMutable();
          super.addAll(values, field_);
          onChanged();
        } else {
          fieldBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearField() {
        if (fieldBuilder_ == null) {
          field_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          fieldBuilder_.clear();
        }
        return this;
      }
      public Builder removeField(int index) {
        if (fieldBuilder_ == null) {
          ensureFieldIsMutable();
          field_.remove(index);
          onChanged();
        } else {
          fieldBuilder_.remove(index);
        }
        return this;
      }
      public org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.Builder getFieldBuilder(
          int index) {
        return getFieldFieldBuilder().getBuilder(index);
      }
      public org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormatOrBuilder getFieldOrBuilder(
          int index) {
        if (fieldBuilder_ == null) {
          return field_.get(index);  } else {
          return fieldBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormatOrBuilder> 
           getFieldOrBuilderList() {
        if (fieldBuilder_ != null) {
          return fieldBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(field_);
        }
      }
      public org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.Builder addFieldBuilder() {
        return getFieldFieldBuilder().addBuilder(
            org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.getDefaultInstance());
      }
      public org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.Builder addFieldBuilder(
          int index) {
        return getFieldFieldBuilder().addBuilder(
            index, org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.getDefaultInstance());
      }
      public java.util.List<org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.Builder> 
           getFieldBuilderList() {
        return getFieldFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat, org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.Builder, org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormatOrBuilder> 
          getFieldFieldBuilder() {
        if (fieldBuilder_ == null) {
          fieldBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat, org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.Builder, org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormatOrBuilder>(
                  field_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          field_ = null;
        }
        return fieldBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:MetastoreValueFormat)
    }
    
    static {
      defaultInstance = new MetastoreValueFormat(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:MetastoreValueFormat)
  }
  
  public interface MetastoreFieldFormatOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string key = 1;
    boolean hasKey();
    String getKey();
    
    // optional bytes value = 2;
    boolean hasValue();
    com.google.protobuf.ByteString getValue();
  }
  public static final class MetastoreFieldFormat extends
      com.google.protobuf.GeneratedMessage
      implements MetastoreFieldFormatOrBuilder {
    // Use MetastoreFieldFormat.newBuilder() to construct.
    private MetastoreFieldFormat(Builder builder) {
      super(builder);
    }
    private MetastoreFieldFormat(boolean noInit) {}
    
    private static final MetastoreFieldFormat defaultInstance;
    public static MetastoreFieldFormat getDefaultInstance() {
      return defaultInstance;
    }
    
    public MetastoreFieldFormat getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.bookkeeper.proto.ZKMetaFormats.internal_static_MetastoreFieldFormat_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.bookkeeper.proto.ZKMetaFormats.internal_static_MetastoreFieldFormat_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }
    
    private void initFields() {
      key_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, value_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.bookkeeper.proto.ZKMetaFormats.internal_static_MetastoreFieldFormat_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.bookkeeper.proto.ZKMetaFormats.internal_static_MetastoreFieldFormat_fieldAccessorTable;
      }
      
      // Construct using org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.getDescriptor();
      }
      
      public org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat getDefaultInstanceForType() {
        return org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.getDefaultInstance();
      }
      
      public org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat build() {
        org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat buildPartial() {
        org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat result = new org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat) {
          return mergeFrom((org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat other) {
        if (other == org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string key = 1;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
      }
      
      // optional bytes value = 2;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:MetastoreFieldFormat)
    }
    
    static {
      defaultInstance = new MetastoreFieldFormat(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:MetastoreFieldFormat)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MetastoreValueFormat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MetastoreValueFormat_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MetastoreFieldFormat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MetastoreFieldFormat_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"src/main/proto/ZKMetaFormats.proto\"<\n\024" +
      "MetastoreValueFormat\022$\n\005field\030\001 \003(\0132\025.Me" +
      "tastoreFieldFormat\"2\n\024MetastoreFieldForm" +
      "at\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\014B\037\n\033org.ap" +
      "ache.bookkeeper.protoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MetastoreValueFormat_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MetastoreValueFormat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MetastoreValueFormat_descriptor,
              new java.lang.String[] { "Field", },
              org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat.class,
              org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreValueFormat.Builder.class);
          internal_static_MetastoreFieldFormat_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MetastoreFieldFormat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MetastoreFieldFormat_descriptor,
              new java.lang.String[] { "Key", "Value", },
              org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.class,
              org.apache.bookkeeper.proto.ZKMetaFormats.MetastoreFieldFormat.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
